# Generated by Django 5.0.3 on 2024-03-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_correct_answer_question_option5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option5',
            new_name='correct_option',
        ),
    ]
