# Generated by Django 5.0.3 on 2024-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_option5_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='displayed_questions',
            field=models.ManyToManyField(blank=True, related_name='displayed_in_tests', to='app.question'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='wrong_answers',
            field=models.ManyToManyField(blank=True, related_name='wrong_answers', to='app.question'),
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='attempted_questions',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='testresult',
            name='attempted_questions',
            field=models.ManyToManyField(blank=True, related_name='attempted_in_tests', to='app.question'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_answers',
            field=models.ManyToManyField(blank=True, related_name='correct_answers', to='app.question'),
        ),
    ]
