# Generated by Django 5.0.3 on 2024-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_testresult_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
