# Generated by Django 5.0.3 on 2024-03-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_testresult_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='time_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
