# Generated by Django 5.0.3 on 2024-03-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_testresult_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.CharField(default='0m os', max_length=255),
            preserve_default=False,
        ),
    ]
